name: ci-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome step
        run: echo "Welcome to the GH Actions"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Repository Information
        run: |
           echo "Repository Name: ${{github.repository}}"
           echo "Type of Event: ${{github.event_name}}"
           git --version
           git branch
           git log






